FROM docker.io/rocm/pytorch:rocm6.4.2_ubuntu24.04_py3.12_pytorch_release_2.6.0 as builder

WORKDIR /app

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY fine_tuning_amd.py .
COPY dataset.jsonl .


FROM docker.io/rocm/pytorch:rocm6.4.2_ubuntu24.04_py3.12_pytorch_release_2.6.0

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

COPY --from=builder /app/fine_tuning_amd.py .
COPY --from=builder /app/dataset.jsonl .

ENV PATH="/opt/venv/bin:$PATH"

CMD ["python", "fine_tuning_amd.py"]
