apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: st-model-cache
  namespace: barzel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path-data

